overrides:
  - files:
      - '*.ts'
    env:
      browser: true
      es2021: true
    extends: standard-with-typescript
    parserOptions:
      project: './tsconfig.json'
      ecmaVersion: latest
      sourceType: module
    rules: 
      array-bracket-spacing: [error, always]
      object-curly-spacing: [error, always]
      semi: [error, never]
      "@typescript-eslint/no-extraneous-class": off
      "@typescript-eslint/explicit-function-return-type": off
      "@typescript-eslint/no-misused-promises": off
      "@typescript-eslint/strict-boolean-expressions" : off
      "@typescript-eslint/naming-convention":
        - error
        - selector: variable
          format: 
            - camelCase
            - UPPER_CASE
            - snake_case
        - selector: function
          format: 
            - camelCase
            - PascalCase
            - snake_case
        - selector: typeLike
          format: 
            - PascalCase
            - snake_case
