env:
  browser: true
  es2021: true
extends: standard-with-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  array-bracket-spacing: [error, always]
  object-curly-spacing: [error, always]
  semi: [error, never]
