version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/test
  web:
    depends_on:
      - db
    build: .
    ports:
      - "3000:3000"
volumes:
  db_data: