name: Raspberry Pi Deployment Pipeline

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build
        run: npm install && npm run build

      # You can skip the zip step if you are directly pulling and building on the Raspberry Pi

      - name: "Push to server"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.RASPI_SSH_HOST }}
          username: ${{ secrets.RASPI_SSH_USERNAME }}
          password: ${{ secrets.RASPI_SSH_KEY }}
          port: ${{ secrets.RASPI_SSH_PORT }}
          source: "dist/"
          strip_components: 1
          target: "/Documents/PROG/basic_rest_api/"